//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scholarship_Application.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int studentid { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        public string emailaddress { get; set; }
        public System.DateTime birthdate { get; set; }
        public string nationalid { get; set; }
        public string university { get; set; }
        public string major { get; set; }
        public double gpa { get; set; }
        public string resumepath { get; set; }
        public Nullable<int> userid { get; set; }
        public Nullable<bool> isaccept { get; set; }
    
        public virtual User User { get; set; }
    }
}
